### ISSUE TITLE
Issue in building

### ISSUE THREAD

**Issue by yash-15** [PositronicsLab/Moby#8]
I tried to build from source as:
```
git clone https://github.com/PositronicsLab/Moby 
cd Moby/
mkdir build
cd build
cmake ..
```
But I get the following error:
```
CMake Error at CMakeModules/FindRavelin.cmake:31 (message):
  FindRavelin: Could not find VectorNd.h
Call Stack (most recent call first):
  CMakeLists.txt:62 (find_package)
```
Please help.

**Comment by edrumwri** [comment]
Hi Yash,

I updated the wiki page for Moby to make it clearer that Ravelin (https://github.com/PositronicsLab/Ravelin) must be installed first. Please do let us know if you require additional assistance.
