### ISSUE TITLE
Could not find <Moby/EulerIntegrator.h> 

### ISSUE THREAD

**Issue by Linjackffy** [PositronicsLab/Moby#9]
Hi, I have a problem when compiling openrave. The console message is like this:
`In file included from /root/git/openrave/plugins/mobyrave/mobyrave.cpp:16:0:
/root/git/openrave/plugins/mobyrave/mobyphysics.h:22:10: fatal error: Moby/EulerIntegrator.h: not such file or folder
 #include <Moby/EulerIntegrator.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
plugins/mobyrave/CMakeFiles/mobyrave.dir/build.make:62: recipe for target 'plugins/mobyrave/CMakeFiles/mobyrave.dir/mobyrave.cpp.o' failed
make[2]: *** [plugins/mobyrave/CMakeFiles/mobyrave.dir/mobyrave.cpp.o] Error 1
CMakeFiles/Makefile2:1497: recipe for target 'plugins/mobyrave/CMakeFiles/mobyrave.dir/all' failed
make[1]: *** [plugins/mobyrave/CMakeFiles/mobyrave.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
`
The version of openrave is 7c5f5e27eec2b2ef10aa63fbc519a998c276f908, and the version of Moby is the lastest version.

Looking forward to your reply!

**Comment by edrumwri** [comment]
Hi @Linjackffy the error message looks to be a problem with openrave's Moby installation. Specifically, it seems that openrave is not including the path to Moby/include when compiling with gcc/clang. If Moby were installed in $HOME/openrave/plugins/mobyrave, for example, you'd expect to see something like this with gcc:

g++ -I$HOME/openrave/plugins/mobyrave/include <other compilation options here...>

You might also be having problems b/c you're trying to build/install in root.

Best of luck,
E
